# 自动求导


In [36]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [37]:
x.requires_grad_(True) # 等价于 x.requires_grad = True
x.grad

In [38]:
y = 2 * torch.dot(x, x) 
y

tensor(28., grad_fn=<MulBackward0>)

In [39]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [40]:
x.grad == 4 * x

tensor([True, True, True, True])

### 现在让我们计算x的另一个函数

In [41]:
# 在默认情况下，PyTorch会累加梯度。因此，我们需要在每次反向传播之前清空梯度
x.grad.zero_() # 清空梯度
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [42]:
# 对非标量调用`backward`需要传入一个`gradient`参数来指定求导的方向
x.grad.zero_()
y = x * x
# 等价于 y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [43]:
# 将某些计算移动到计算图之外
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [44]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])